---
title: "SVN DIABETES"
author: "Nii Adjetey Adjei-Annan"
date: "2024-04-19"
output: html_document
---
```{r}
diabetes2.csv=read.csv("diabetes2.csv")
names(diabetes2.csv)
```


```{r}
dim(diabetes2.csv)
train=sample(1:887, 0.7*887)
train_data=diabetes2.csv[train,]
test_data=diabetes2.csv[-train,]  
```


```{r}
library(e1071)
library(ROCR)

```



```{r}
svm_linear=svm(Outcome~., data=train_data, kernel="linear",cost=5,type="C-classification")
summary(svm_linear)
```



```{r}
ypred <-predict(svm_linear, test_data)
cm=table(predict = ypred, truth=test_data$Outcome)
cm
sum(diag(cm))/sum(cm)
```


### Roc curve

#### In order to obtain the fitted values for a given SVM model fit, we use decision.values = TRUE when fitting svm(). Then the predict() function will output the fitted values.

```{r}
svm_linear1=svm(Outcome~., data=train_data, kernel="linear",type="C-classification",cost=2,decision.values=TRUE)
#summary(svm_linear1)
fitted1 <-attributes(predict(svm_linear1, test_data, decision.values = TRUE))$decision.values
#fitted[1:10]
predicted_obj <-prediction(fitted1, test_data$Outcome)
perf <-performance(predicted_obj, "tpr", "fpr")
plot(perf,col="red")
abline(0,1,col="purple")
auc=performance(predicted_obj,"auc" )
auc@y.values
legend(0.8,0.2,print("AUC=0.82"))
```



#### We can perform cross-validation using tune() to select the best choice of cost for an SVM with a linear kernel:
```{r}
set.seed(1)
tune.out1 <-tune(svm,Outcome~., data = train_data,kernel = "linear",ranges=(cost = c(0.1, 1,10,50)))
summary(tune.out1)
```

